// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.TestRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontLeft;
    public static SpeedController driveTrainFrontRight;
    public static SpeedController driveTrainRearLeft;
    public static SpeedController driveTrainRearRight;
    public static RobotDrive driveTrainRobotDrive;
    public static Solenoid gripperSolenoid;
    public static SpeedController winchMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeft = new Talon(2);
        LiveWindow.addActuator("Drive Train", "Front Left", (Talon) driveTrainFrontLeft);
        
        driveTrainFrontRight = new Talon(3);
        LiveWindow.addActuator("Drive Train", "Front Right", (Talon) driveTrainFrontRight);
        
        driveTrainRearLeft = new Talon(1);
        LiveWindow.addActuator("Drive Train", "Rear Left", (Talon) driveTrainRearLeft);
        
        driveTrainRearRight = new Talon(0);
        LiveWindow.addActuator("Drive Train", "Rear Right", (Talon) driveTrainRearRight);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainFrontLeft, driveTrainRearLeft,
              driveTrainFrontRight, driveTrainRearRight);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        gripperSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Gripper", "Solenoid", gripperSolenoid);
        
        winchMotor = new Jaguar(4);
        LiveWindow.addActuator("Winch", "Motor", (Jaguar) winchMotor);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
